### ISSUE TITLE
Can i change start time and end time in DayView?

### ISSUE THREAD

**Issue by huynguyen96419** [SimformSolutionsPvtLtd/flutter_calendar_view#298] opened 2023-11-27 04:46 UTC
![Screenshot 2023-11-27 at 11 44 13 AM](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/127708425/a723adc9-6504-45a6-8142-e49f6091fc4d)
By the default, the time range of the DayView from 00:00 -> 24:00, so can i change to 08:00 -> 20:00?
Thank you so much!

**Comment by laguerreuy** [comment] 2024-01-27 13:49
Same question! 
Awesome widget by the way

**Comment by Adm94** [comment] 2024-03-29 11:03
yes you with the startHour option but there is no endHour option
```
DayView<Event>(
 startHour: 8,
)
```

**Comment by apurva010** [comment] 2024-05-08 04:46
Close this issue as it is duplicate of #240.

**Closed by apurva010** 2024-05-08 04:46 UTC
