### ISSUE TITLE
Cell error in week view

### ISSUE THREAD

**Issue by Willy14mx** [SimformSolutionsPvtLtd/flutter_calendar_view#98] opened 2022-08-29 12:30 UTC
Events are stacked incorrectly, they are stacked on one side of the container without using the full width of the cell, which causes that you only see 2 colored lines when they could be expanded more.

![WhatsApp Image 2022-08-29 at 2 06 46 PM](https://user-images.githubusercontent.com/78026333/187201244-a0dd03d5-0c54-48f0-9f6f-5cc67ad0451b.jpeg)

**Comment by PRBaraiya** [comment] 2022-08-31 06:12
@Willy14mx Please share reproducible code snippet.

**Comment by PRBaraiya** [comment] 2023-01-04 07:07
Closing this issue as We were not able to reproduce it. @Willy14mx Feel free to reopen it if you are still facing this issue and share the reproducible code with it.

**Closed by PRBaraiya** 2023-01-04 07:07 UTC
Labels: more-info-required, waiting-for-resoponse
