### ISSUE TITLE
Web - week view  layout issue

### ISSUE THREAD

**Issue by harbignote** [SimformSolutionsPvtLtd/flutter_calendar_view#121] opened 2022-09-29 13:55 UTC
Dear Simform Solutions,

Im Facing  in issue in the week view when it shows in web view.
as shown in [this image](https://ibb.co/NLnDWCV) 
im using it with[ fluent_ui](https://github.com/bdlukaa/fluent_ui)  i dont know if it help to check it

`══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during layout:
The specific RenderFlex in question is: RenderFlex#23156 relayoutBoundary=up2 OVERFLOWING:
  creator: Row ← SizedBox ← Column ← ConstrainedBox ← Container ←
    InternalWeekViewPage<Object?>-[<'602022-09-26 00:00:00.000'>] ← ValueListenableBuilder<bool> ←
    RepaintBoundary ← IndexedSemantics ← _SelectionKeepAlive ←
    NotificationListener<KeepAliveNotification> ← KeepAlive ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=895.0, 0.0<=h<=Infinity)
  size: Size(895.0, 45.0)
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: start
  textDirection: ltr
  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: A RenderFlex overflowed by 265 pixels on the right.
Another exception was thrown: A RenderFlex overflowed by 415 pixels on the right.
Another exception was thrown: A RenderFlex overflowed by 265 pixels on the right.`

**Comment by ParthBaraiya** [comment] 2022-11-04 18:15
@harbignote image you shared is not accessible. And also, if possible please share a reproducible code.

**Comment by PRBaraiya** [comment] 2023-01-04 07:09
Hi, @harbignote I'm closing this issue as we were not able to reproduce it in the latest version. Feel free to reopen this issue if you are still facing it.

**Closed by PRBaraiya** 2023-01-04 07:09 UTC
Labels: bug, waiting-for-resoponse, priority:3
