### ISSUE TITLE
Event that starts and ends on next day is not shown in the view by day and week

### ISSUE THREAD

**Issue by PabloCir** [SimformSolutionsPvtLtd/flutter_calendar_view#196] opened 2023-02-24 05:04 UTC
If I create an event that starts on one day and ends, for example, at dawn the next day, it is not shown in the week and day view, since the dates are well set.
![image](https://user-images.githubusercontent.com/47547913/221096423-0478e6dd-4479-4c77-acb9-b68545803010.png)

**Comment by PRBaraiya** [comment] 2023-03-13 04:29
Duplicate of #171 .

**Closed by PRBaraiya** 2023-03-13 04:29 UTC
