### ISSUE TITLE
Handling of events spanning more than one day

### ISSUE THREAD

**Issue by kaidrumm** [SimformSolutionsPvtLtd/flutter_calendar_view#220] opened 2023-04-26 21:37 UTC
I called EventController._addAll with an events list that contained one event with the start and end on different days:
{date: 2023-04-19 19:00:00.972, startTime: 2023-04-19 19:00:00.972, endTime: 2023-04-20 07:00:00.643, event: Instance of 'Calendar', title: Busy Day 2, description: , endDate: 2023-04-19 19:00:00.972}

Start is 4/19 at 19:00
End is 4/20 at 7:00

MergeEventArranger threw the error: 
I/flutter (11963): Failed to add event because of one of the given reasons: 
I/flutter (11963): 1. Start time or end time might be null
I/flutter (11963): 2. endTime occurs before or at the same time as startTime.

This is happening because in merge_event_arranger, you check getTotalMinutes on lines 27 & 28. That only counts the minutes since midnight for each DateTime. 

Is the calendar intended to support an event that spans two different days?

**Comment by ParthBaraiya** [comment] 2023-05-06 18:45
Hello @kaidrumm , We are planning this to add this in future.

I'm closing this issue as this is duplicate of #23 .

**Closed by ParthBaraiya** 2023-05-06 18:45 UTC
