### ISSUE TITLE
how to get time with offset use y 

### ISSUE THREAD

**Issue by kapilsharma-gts** [SimformSolutionsPvtLtd/flutter_calendar_view#243] opened 2023-07-23 07:21 UTC

**Comment by jaiminrana05** [comment] 2023-08-02 14:24
Hi,@kapilsharma-gts Can you please elaborate more on what is the issue?

**Comment by vatsaltanna** [comment] 2023-08-04 05:37
Closing this issue as It seems to be duplicate of #244 .

**Closed by vatsaltanna** 2023-08-04 05:37 UTC
Labels: waiting-for-resoponse
