### ISSUE TITLE
Weird behaviour when using a NavigationRail

### ISSUE THREAD

**Issue by maelchiotti** [SimformSolutionsPvtLtd/flutter_calendar_view#201] opened 2023-03-02 09:53 UTC
My app displays a navigation rail on desktop and web and calendar_view has a weird behavior.

DayView seems to work at first glance, but when adding an event it is missaligned.

WeekView triggers a RenderFlex overflow.

You can reproduce this by creating a new Flutter project and using this build method (using either view):

```dart
@override
  var now = DateTime.now();
    final event = CalendarEventData(
        date: DateTime.now(),
        event: "Event 1",
        title: 'Event 1',
        startTime: now,
        endTime: DateTime(now.year, now.month, now.day, 16, 30));
    CalendarControllerProvider.of(context).controller.add(event);
    return Scaffold(
      body: Row(
        children: [
          NavigationRail(destinations: const [
            NavigationRailDestination(icon: Icon(Icons.home), label: Text('Home')),
            NavigationRailDestination(icon: Icon(Icons.settings), label: Text('Settings'))
          ], selectedIndex: _selectedIndex),
          Expanded(child: DayView()),
        ],
      ),
    );
  }
```

![week_view](https://user-images.githubusercontent.com/44336112/222403775-04063bb8-19e8-4b56-9358-60b69bfa9b88.png)

![day_view](https://user-images.githubusercontent.com/44336112/222403779-816a2a49-c86c-40e4-8e14-3bbfc930d922.png)

**Comment by maelchiotti** [comment] 2023-03-02 15:38
Qick fix: use a `LayoutBuilder` to specify the width of the View. Fixes both DayView and WeekView.

```dart
@override
Widget build(BuildContext context) {
  return Expanded(
    child: LayoutBuilder(builder: (context, constraints) {
      return DayView(
        width: constraints.maxWidth,
      );
    }),
  );
}
```

**Comment by PRBaraiya** [comment] 2023-03-13 04:07
Thanks for the solution @maelchiotti, That is the solution for now. 

The issue is occurring because you were not providing width. If width is not provided to any calendar view it by default takes the width of the MediaQuery. and in the case of the navigation rail available width for the calendar view is less than the width of the MediaQuery. So, If possible always provide width to the calendar view.

I'm closing this issue for now. If there is a more efficient way to provide the size of the calendar view we will implement it in the future.

**Closed by PRBaraiya** 2023-03-13 04:07 UTC
