### ISSUE TITLE
Adding a key to weekView breaks page changes

### ISSUE THREAD

**Issue by opsiv** [SimformSolutionsPvtLtd/flutter_calendar_view#236] opened 2023-06-20 13:15 UTC
My calendar won't switch pages correctly after adding a global key after adding it as explained in #22:
`WeekView` like that:
```dart
final weekViewKey = GlobalKey<WeekViewState>();

  @override
  Widget build(BuildContext context) {
    return WeekView<TaskBl>(
        key: weekViewKey,
...
```
Here's a comparison [with](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/98770161/4064e8fa-e76b-4e05-ae55-d0828e709aa8) and [without](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/98770161/313b1075-1b3c-4af3-9f63-03aab24505bc) the key added in the code:

The behavior looks like a potential bug to me, or am I doing something wrong?

**Comment by jaiminrana05** [comment] 2023-08-03 16:33
Hi, @opsiv  can you please share your entire code? Because I'm not able to reproduce it using example app

**Comment by PRBaraiya** [comment] 2023-11-01 15:03
Closing this issue as it's not reproducible.

**Closed by PRBaraiya** 2023-11-01 15:03 UTC
Labels: waiting-for-resoponse
