### ISSUE TITLE
disabled time periods

### ISSUE THREAD

**Issue by MichalNemec** [SimformSolutionsPvtLtd/flutter_calendar_view#128] opened 2022-10-26 11:09 UTC
Hello, how can i create disabled periods of time on a weekview?
How can i tap in weekview to create an event?

**Comment by ParthBaraiya** [comment] 2022-11-19 16:25
@MichalNemec For now package does not provide any callback on tap. There is one callback for long press that you can use.

**Comment by ParthBaraiya** [comment] 2022-11-19 16:26
Duplicate of #50 .

**Closed by ParthBaraiya** 2022-11-19 16:26 UTC
