### ISSUE TITLE
'onDateTap' not working properly when 'startHour' is set

### ISSUE THREAD

**Issue by DonnyDevIT** [SimformSolutionsPvtLtd/flutter_calendar_view#355] opened 2024-05-06 08:45 UTC
I have an agenda that I set 'startHour: 6' because I want the time to start for 6am

When I click on an empty slot, the date of the click is not right, if I click 6am I get 0am, if I click 7am I get 1am an so on.

So the problem is even if I use 'startHour' in the 'onDateTap' function I have to make a fix for making it kick the right date.

`...
date = date.add(Duration(hours: 6)); //Fix starting point
...`
I added the same value of 'startHour' so the click hour is right. here some images

Screenshot agenda
<img width="1769" alt="Screenshot agenda" src="https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/87426979/a6a03a8a-e954-43cb-866f-560c026effde">

I click 7am with no fix
<img width="1769" alt="I click 7am with no fix" src="https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/87426979/eb31205b-1901-4fcb-a594-0c4443600caa">

I click 7am with fix
<img width="1769" alt="I click 7am with fix" src="https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/87426979/cd720100-3f41-4f8c-b8a7-ea9658ee2807">

**Comment by DonnyDevIT** [comment] 2024-05-06 12:26
Also the current time bullet is bugged due to that
<img width="1702" alt="Screenshot 2024-05-06 alle 14 25 51" src="https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/87426979/bd592230-d9b1-4d93-9a19-911c6660897c">

**Comment by apurva010** [comment] 2024-05-07 06:53
This issue is duplicate of other one(#341) and it is already fixed in #350. So I am closing this issue.

**Closed by apurva010** 2024-05-07 06:53 UTC
Labels: duplicate

**Comment by DonnyDevIT** [comment] 2024-05-07 07:23
Ok, I wait for the fix :) May i ask a question? @apurva010 ?

Can you guys implement a 3days view? I really need it and the week view using 3weekdays not works properly
