### ISSUE TITLE
Calendar not maintaining state

### ISSUE THREAD

**Issue by Raviteja11122** [SimformSolutionsPvtLtd/flutter_calendar_view#127] opened 2022-10-19 05:15 UTC
I switched between views it not storing previous visited month/week/day every time it showing initial passed date.

**Comment by ParthBaraiya** [comment] 2022-11-04 19:09
@Raviteja11122 Please share reproducible code.

**Comment by PRBaraiya** [comment] 2023-01-04 07:10
Hi, @Raviteja11122  I'm closing this issue as we were not able to reproduce it. Feel free to reopen this issue if you are still facing it.

**Closed by PRBaraiya** 2023-01-04 07:10 UTC
Labels: waiting-for-resoponse
