### ISSUE TITLE
Hide days from previois and next month in month view

### ISSUE THREAD

**Issue by nelci592** [SimformSolutionsPvtLtd/flutter_calendar_view#328] opened 2024-02-28 13:11 UTC
In the month view, I want to display the days only for the current month. I don't want to display the last days from the previous month and the first days from the next month.
Thank you.

**Comment by apurva010** [comment] 2024-05-08 04:43
Close this issue as it is duplicate of #141.

**Closed by apurva010** 2024-05-08 04:43 UTC
